project:
  type: book
  output-dir: "docs"

book:
  title: "Estatística Aplicada à Pesca e Aquicultura com R"
  author: "Evaldo Martins da Silva"
  date: "14/04/2025"
  cover-image: images/capa3.png
  chapters:
    - index.qmd
    - intro.qmd
    - capitulos/capitulo1/estatistica_descritiva.qmd
    - capitulos/capitulo2/probabilidades.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    lang: pt-BR
  pdf:
    documentclass: scrreprt
    lang: pt-BR

editor: visual


