project:
  type: book
  output-dir: "docs"

book:
  title: "Estatística Aplicada à Pesca e Aquicultura com R"
  author: "Evaldo Martins da Silva"
  date: "14/04/2025"
  cover-image: images/capa3.png
  chapters:
    - index.qmd
    - capitulos/capitulo01/intro.qmd
    - capitulos/capitulo02/criacao_ambiente_computacional.qmd
    - capitulos/capitulo03/organizacao_projetos_leitura_dados.qmd
    - capitulos/capitulo04/tratamento_basico_dados_visualizacao.qmd
    - capitulos/capitulo05/analise_exploratoria_statistica_descritiva.qmd
    - capitulos/capitulo06/planejamento_amostral_delineamentos_experimentos.qmd
    - capitulos/capitulo07/testes_parametricos_uma_duas_amostras.qmd
    - capitulos/capitulo08/nao-parametricos_uma_duas_amostras.qmd
    - capitulos/capitulo09/regressao_linear_simples_multipla.qmd
    - capitulos/capitulo10/analise_correlacao_associacao_variaveis.qmd
    - capitulos/capitulo11/anova_estudos_observacionais_experimentais.qmd
    - capitulos/capitulo12/ancova_comparacoes_inclinacoes.qmd
    - capitulos/capitulo13/analise_regressao_nao_linear.qmd
    - capitulos/capitulo14/analise_series_temporais.qmd
    - capitulos/capitulo15/modelos_lineares_generalizados.qmd
    - capitulos/capitulo16/analise_modelos_efeitos_mistos.qmd
    - capitulos/capitulo17/analise_multivariada_dados.qmd
    - capitulos/capitulo18/criacao_mapas_em_R.qmd
    - capitulos/capitulo19/metodologia_superfície_respostas.qmd
    - capitulos/capitulo20/modelos_dinamica_populacional_aplicados.qmd
    - capitulos/capitulo21/relatorios_comunicacao_dados_usando_quarto.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    lang: pt-BR
  pdf:
    documentclass: scrreprt
    lang: pt-BR

editor: visual


